### ISSUE TITLE
App Expired?

### ISSUE THREAD

**Issue by djbooya** [visnkmr/timenetspeed#10]
Since 7/31/2021 the app does not run and says it has expired.  Can it be re-published/updated?

**Comment by visnkmr** [comment]
Hey,
Thanks for alerting me to the issue. As notified on [telegram channel](https://t.me/vishnunkmr), an update should now be live on amazon appstore that addresses this issue. The release schedule may vary based on region, if not available within 24 hours pl do get back to us.

**Comment by djbooya** [comment]
Juts after I opened bug I saw the telegram update and everything is good
again, thanks!
