### ISSUE TITLE
Device date error

### ISSUE THREAD

**Issue by adeep** [visnkmr/timenetspeed#13]
Hi, I am using Realme 4k Stick.
Today app gives date error. My date is correct as seen but app is giving error. There is no update on Playstore. 
I don't know what to do.
![Screenshot_20230315-185025](https://user-images.githubusercontent.com/374042/225368472-ff6f4f4d-0061-46bc-9a92-ce9f640fa35e.png)

**Comment by visnkmr** [comment]
Thanks for notifying us regarding the issue. An update has been pushed to Amazon Appstore and Google Play. The Play store update should be available within 1 day, the amazon one can take longer.
