### ISSUE TITLE
Your device time is incorrect

### ISSUE THREAD

**Issue by prasannasekhar** [visnkmr/timenetspeed#15]
It was working properly in my old fire stick. I got a new fire stick 4k max and installed the time Netspeed and it is not working. I have enable the adb debugging on and given proper permission. Once I open the app and click on the Show time I get an error saying your device time is incorrect. If your device time is correct then you are using an obsolete version of the app. The version shown is 0.19A7i(32). I got a similar issue in the old device and it was fixed with some update from your side but again seeing this error with the new device

**Comment by visnkmr** [comment]
Thanks for notifying us regarding the issue. An update has been pushed to Amazon Appstore yesterday. The update should be available within 2 days.

**Comment by visnkmr** [comment]
The issue should have been fixed with the latest update available via amazon appstore.
