### ISSUE TITLE
Overlay out of screen border

### ISSUE THREAD

**Issue by Th3BiSh0p** [visnkmr/timenetspeed#2]
Hello, I have been using the time overlay for a long time and it stopped to work. I manage to get it working again with the adb thing but now the time is cropped, I can't see it because it is mostly out of the screen borders.

Fire OS 5.2.7.3

**Comment by visnkmr** [comment]
This issue should have been fixed in the latest release available [here](https://github.com/visnkmr/timenetspeed/releases/latest).

**Comment by visnkmr** [comment]
For those that face similar issue; The way to fix this is to add overscan margin.
