### ISSUE TITLE
[new feature] Switch to show time/speed only on start screen or any screen

### ISSUE THREAD

**Issue by joergi** [visnkmr/timenetspeed#3]
Hi,
I have a possible feature:
I would like to see the time on my screen on the fire TV, but only during the start screen or any other "regular" fire TV screen, but if I start an app, it should not be shown anymore.

Thanks a lot
Joergi

**Comment by visnkmr** [comment]
This is possible to implement in older versions of android upto Android 6 but in newer version the amount of work required to implement it just would not be worth it in the end; unless of course amazon integrates it as a system app; or provide a simpler API to implement this functionality.

Feel free to guide us; if you know of any other implementations of this feature.

**Comment by joergi** [comment]
Okay, thank you (but no idea.... )
thanks anyway!
