### ISSUE TITLE
App not working in Amazon 3rd Gen

### ISSUE THREAD

**Issue by thisisjagan** [visnkmr/timenetspeed#5]
Unable to use the app in 3rd Gen Amazon firestick. Looks like Overlay settings is disabled.

**Comment by visnkmr** [comment]
Hey,
Fire TV OS 6 and above lacks the settings options to be able to enable Overlay permission for any app, so, you can use [this](https://appchoose.blogspot.com/p/time-netspeed-overlay-adb-help-for.html) method to enable overlay permission for the app in order for it to be able to display Time and Netspeed on your TV.

If you encounter further issues do let us know here.

Thanks.

**Comment by thisisjagan** [comment]
It works. Thank you so much. You can include this information in the app itself.
