### ISSUE TITLE
1.2A3i is expired

### ISSUE THREAD

**Issue by petersloan** [visnkmr/timenetspeed#55]
This version is no longer loading. Curious what the reason for the time bomb given it was last updated in June of this year.

**Comment by visnkmr** [comment]
update has been pushed to amazon appstore and our appstore.

_On our appstore updates are available immediately.
Amazon appstore update takes 0-3 days to be available._

**Comment by goooglefc** [comment]
How to update from your appstore?

**Comment by petersloan** [comment]
Resolving as time bomb was updated.
